words = [
    "astro",
    "checkhealth",
    "claudecode",
    "codeium_os",
    "colorscheme",
    "config",
    "cterm",
    "cursorcolumn",
    "cursorline",
    "dap",
    "edheltzel",
    "fd",
    "folke",
    "github",
    "gitsigns",
    "gopls",
    "heltzel",
    "htmldjango",
    "https",
    "js",
    "keymap",
    "keymaps",
    "laststatus",
    "lazygit",
    "lazyvim",
    "lsp",
    "lua",
    "lualine",
    "neoed",
    "neovim",
    "nvim",
    "opencode",
    "ripgrep",
    "scrolloff",
    "spelllang",
    "statusline",
    "supermaven",
    "swapfile",
    "typescript",
    "undodir",
    "undofile",
    "vscode",
    "vspacecode",
    "vue",
    "xclip",
]
